# Generated by Django 4.1 on 2022-09-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price',
            new_name='decription',
        ),
        migrations.AddField(
            model_name='products',
            name='upload',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
