# Generated by Django 4.1 on 2022-09-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0003_products_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='decription',
            new_name='description',
        ),
    ]
