# Generated by Django 4.1 on 2022-09-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0005_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='productid',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
