# Generated by Django 4.1 on 2022-09-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0006_products_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='productid',
        ),
        migrations.AddField(
            model_name='buying',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
