# Generated by Django 4.1 on 2022-11-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0009_alter_buying_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='buying',
            name='userratings',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
