# Generated by Django 4.1 on 2022-11-30 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homestoreapp', '0011_remove_buying_userratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=255)),
                ('review_tittle', models.CharField(max_length=255)),
                ('review', models.CharField(max_length=255)),
                ('ownerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestoreapp.owner')),
                ('purchasingitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestoreapp.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestoreapp.customer')),
            ],
        ),
    ]
